# Generated by Django 2.2.7 on 2019-11-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cartel',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
