# Generated by Django 2.2.7 on 2019-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191113_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='photo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cartel',
            field=models.ImageField(upload_to=''),
        ),
    ]
