# Generated by Django 2.2.7 on 2019-11-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191120_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cartel',
            field=models.URLField(),
        ),
    ]
