# Generated by Django 2.2.7 on 2019-11-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191120_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cartel',
            new_name='poster',
        ),
    ]
