# Generated by Django 2.2.7 on 2019-11-25 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191125_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='premieredate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
